meta_name: "Deforestation"
meta_title: "Deforestation - Together aginst deforestation"
meta_description: "Deforestation, the easy solution to monitor your big landfields and areas in order to protect them."
meta_image: "../app/assets/images/deforestation-word-logo.png" # should exist in `app/assets/images/`
# twitter_account: "@your_twitter_account"   # required for Twitter Cards
